### ISSUE TITLE
NPM package is not transpiled to es5

### ISSUE THREAD

**Issue by d4rky-pl** [sindresorhus/p-all#1]
p-all package on NPM is not transpiled to ES5 and uses fat arrow `=>` syntax. Unfortunately this breaks UglifyJS as it does not (yet) support ES6 syntax out of the box. Could you please transpile the package and release a new version so it doesn't break uglify? :)

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
