### ISSUE TITLE
Option to set failOnError false while still throwing first error encountered

### ISSUE THREAD

**Issue by kitsunde** [sindresorhus/p-all#14]
Hello,

I'm using this library to quickly replace calls that are currently `Promise.all` to avoid an issue with orphaned promises after one fails. However this throws an `AggregateError` on `{ failOnError: false }` which changes the semantics.

It would be nice if it could keep the exception semantics, but still wait. I understand I can just replace things with `allSettled` or some such, although that also changes the semantics since the order of failure is lost.

**Comment by sindresorhus** [comment]
It won't leave promises pending with `{stopOnError: true}`. If promises are started, they will continue until they are done, but `pAll` won't await them or include their result. The proper way to handle this is with a `signal`. It should be pretty easy to include that here as it could just be passed down to `p-map`.

You can already solve your use-case by catching the error and re-throwing `error.errors[0]`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError If you need it in multiple places, you could wrap it in the wrapper function.
