### ISSUE TITLE
object rest spread in dep causing rollup issues

### ISSUE THREAD

**Issue by cmawhorter** [sindresorhus/p-all#7]
v3 of p-all bumped indent-string (via aggregate-error) which includes an untranspiled object rest spread call [here](https://github.com/sindresorhus/indent-string/blob/2b77ed6031074b87a7848578377167255ee32a99/index.js#L7) which is causing me issues with rollup.  any chance it could be removed for us _old node_ and browser folks?

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in changing my code. I target Node.js 10, which does support this. If you need support for anything else, it's up to you to transpile.
